FROM gableroux/flutter

LABEL version="1.0.0"
LABEL name="flutter"
LABEL repository="https://github.com/Techno-Disaster/Flutter-Mate"
LABEL homepage="https://github.com/Techno-Disaster/Flutter-Mate"

COPY LICENSE README.md /

ENTRYPOINT ["flutter"]
CMD ["help"]
